name: Go

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15]
        mongodb-version: [4.4]
    
    steps:
    - uses: actions/checkout@v2

    - name: Start MongoDB ${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.2.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go mod download && go build -v ./...
      working-directory: ./notify-service

    - name: Go Test
      run: go test ./... -coverprofile c.out
      working-directory: ./notify-service/src
      env:
        DB_MONGO_HOST: localhost
        DB_MONGO_PORT: 27017
        DB_MONGO_NAME: notif-service
